### ISSUE TITLE
Add Figure referred in the README for RSA algorithm in the RSA program folder

### ISSUE THREAD

**Issue by nateshmbhat** [git-akshat/CNS-Lab#7] opened 2019-11-21 12:32 UTC

**Comment by git-akshat** [comment] 2019-11-21 17:53
The figure is already added for the 12th program in the readme a week ago.

**Comment by git-akshat** [comment] 2019-11-22 04:24
I guess the issue is resolved so I'm closing the issue.

**Closed as completed** 2019-11-22 04:23 UTC
